global:
  scrape_interval: 2m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 2m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 1m
    basic_auth :
      username: username
      password: <password>
    static_configs:
      - targets: ['ip-vm-1:9100']
      - targets: ['ip-vm-2:9100']